"""Reusable FastAPI dependencies (dependency injection wiring)."""

from app.dependencies.common import (
    CandidateServiceDep,
    DBSession,
    DecisionServiceDep,
    DNAServiceDep,
    DocumentServiceDep,
    ExplanationServiceDep,
    HiddenSkillServiceDep,
    JobServiceDep,
    RankingServiceDep,
    SettingsDep,
    SimulationServiceDep,
    get_candidate_engine,
    get_decision_engine,
    get_dna_engine,
    get_document_engine,
    get_explainability_engine,
    get_file_storage,
    get_hidden_skill_engine,
    get_job_engine,
    get_knowledge_graph,
    get_llm_manager,
    get_prompt_manager,
    get_simulation_service,
)

__all__ = [
    "CandidateServiceDep",
    "DBSession",
    "DecisionServiceDep",
    "DNAServiceDep",
    "DocumentServiceDep",
    "ExplanationServiceDep",
    "HiddenSkillServiceDep",
    "JobServiceDep",
    "RankingServiceDep",
    "SettingsDep",
    "SimulationServiceDep",
    "get_candidate_engine",
    "get_decision_engine",
    "get_dna_engine",
    "get_document_engine",
    "get_explainability_engine",
    "get_file_storage",
    "get_hidden_skill_engine",
    "get_job_engine",
    "get_knowledge_graph",
    "get_llm_manager",
    "get_prompt_manager",
    "get_simulation_service",
]
